title:            Writing Portfolio
description:      A jekyll theme. Because I scribble.
url:              vinsinga.github.io # Site url, without a slash at the end.
signoff:          Vincent Insinga# Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Email
    url:          vinsinga@students.kennesaw.edu
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
